
---

// Spawn coordinates X,Y,Z
Spawn: 0,0,0

// Coordinates of the arena for the first player X,Y,Z
1: 0,0,0
// 1 and 2 arena points for its cleaning. (in the form of a cuboid)
1aX: 0
1aY: 0
1aZ: 0

1bX: 0
1bY: 0
1bZ: 0


// Coordinates of the arena for the second player X,Y,Z
2: 0,0,0
// 1 and 2 arena points for its cleaning. (in the form of a cuboid)
2aX: 0
2aY: 0
2aZ: 0

2bX: 0
2bY: 0
2bZ: 0

// Coordinates of the arena for the third player X,Y,Z
3: 0,0,0
// 1 and 2 arena points for its cleaning. (in the form of a cuboid)
3aX: 0
3aY: 0
3aZ: 0

3bX: 0
3bY: 0
3bZ: 0

// Coordinates of the arena for the fourth player X,Y,Z
4: 0,0,0
// 1 and 2 arena points for its cleaning. (in the form of a cuboid)
4aX: 0
4aY: 0
4aZ: 0

4bX: 0
4bY: 0
4bZ: 0

// Coordinates of the arena for the fifth player X,Y,Z
5: 0,0,0
// 1 and 2 arena points for its cleaning. (in the form of a cuboid)
5aX: 0
5aY: 0
5aZ: 0

5bX: 0
5bY: 0
5bZ: 0

// Coordinates of the arena for the sixth player X,Y,Z
6: 0,0,0
// 1 and 2 arena points for its cleaning. (in the form of a cuboid)
6aX: 0
6aY: 0
6aZ: 0

6bX: 0
6bY: 0
6bZ: 0

// Coordinates of the arena for the seventh player X,Y,Z
7: 0,0,0
// 1 and 2 arena points for its cleaning. (in the form of a cuboid)
7aX: 0
7aY: 0
7aZ: 0

7bX: 0
7bY: 0
7bZ: 0

// Coordinates of the arena for the eigth player X,Y,Z
8: 0,0,0
// 1 and 2 arena points for its cleaning. (in the form of a cuboid)
8aX: 0
8aY: 0
8aZ: 0

8bX: 0
8bY: 0
8bZ: 0

// Coordinates of the arena for the ninth player X,Y,Z
9: 0,0,0
// 1 and 2 arena points for its cleaning. (in the form of a cuboid)
9aX: 0
9aY: 0
9aZ: 0

9bX: 0
9bY: 0
9bZ: 0

// Coordinates of the arena for the teneth player X,Y,Z
10: 0,0,0
// 1 and 2 arena points for its cleaning. (in the form of a cuboid)
10X: 0
10aY: 0
10aZ: 0

10bX: 0
10bY: 0
10bZ: 0
